### ISSUE TITLE
General discussions

### ISSUE THREAD

**Issue by livibetter** [pipeseroni/packaging-aur#1]
This issue is for general discussions about packaging for AUR.  Please note that

* We can discuss anything here, but if the issue is expected to be more than a few comments, do open a new issue and link it.
* For actual works, we will use [Project][project] to track the progress.
* At this moment, only participants would be me, @StefansM, and @Foggalong, we all can edit this issue body, please do edit this to keep issue body up to date, when you add discussions to the list, mark them when complete, update when necessary.
* I am planning to leave Pipeseroni no later than the end of April, whichever comes first, April 30 or the establishment of packaging, that will be the time I leave, no matter what.  I will leave this or any issues I've opened for as long as I could tolerate if they aren't resolved by then.  We might use [Project][project]'s ToDo column, that way, even closed wouldn't matter much.
* Previous discussions: pipeseroni/pipes.sh#29 and Packagers team discussions ([1][pack-1] and [2][pack-2]) (not public accessible, unfortunately)

[project]: https://github.com/pipeseroni/packaging-aur/projects/1
[pack-1]: https://github.com/orgs/pipeseroni/teams/packagers/discussions/1
[pack-2]: https://github.com/orgs/pipeseroni/teams/packagers/discussions/2

## Discussions List

This list is numbered, use the item numbers to refer to any discussions that you wish to discuss.  Note that: this list tracks whether the discussion has resulted a conclusion, not a task list for [actual works][project].

* [ ] 1. Name of this repository
* [x] 2. Organization for each pipe
* [ ] 3. Packaging release process
* [ ] 4. CI, automation?
* [ ] 5. Documentation
* [ ] 6. AUR accounts
* [x] 7. License of this repository (everything, from the `PKGBUILD` to the master branch)

**Comment by livibetter** [comment]
As I am not familiar with AUR, I might be very wrong about anything.

Before I get into my thoughts, I'd like to propose that @StefansM should be the one do the actual works (commits) on the current repository, I will help whatever I can when I have a clear assignments.  Please also note that the current `pipes.c` and `pipes.sh` branches can be deleted or completely rewritten if needed to be.

----

## 1

I kind of like `pipeseroni-aur`, because someday I might see a `pipeseroni` package somewhere.  But for now, `packaging-aur` is okay.

## 2

Currently, we use branches to store `PKGBUILD` for each pipe, although I have seen a few AUR repositories that organize files under directories.  I believe using branches would be better option since we only have a handful of pipes, and the commit history is very clean, they don't mix with other pipes, and no need to specify which pipes we are working on in commit message.

The only minor (and slightly annoying) issue I can see is that GitHub would prompt those green "Compare & pull request" buttons for us.  GitHub might still try to create pull request against `master`, anyone who wishes to contribute will need to manually select the correct branch.

## 3

While trying to understand the packaging, I noticed that there are a few steps must be done when doing a release:

* Updating version string

  @StefansM has [mentioned][1] a way to automate this with `git describe`, if there is no need to change anything in, say pipes.sh's repo, to get that method working, I am all for that.  But I don't know what exactly that needs.

* Updating checksum for integrity check

  I used `updpkgsums`, but it updates with md5sum, can we have hash liks SHA*?  Or do we really need those?  Also, there doesn't seem to have any options for `updpkgsums` to choose.

[1]: https://github.com/orgs/pipeseroni/teams/packagers/discussions/2

* Generating `.SRCINFO`

  From what I understand, we need to re-generate it every time we update `PKGBUILD`, so how do we make sure the file is up to date?


## 4

Do we need CI to check or do anything for us?  If that's possible, and what we need it do for us?

I don't feel we really need CI, but if it can check the validity of `PKGBUILD`, that might be nice, automatically trying to build and install, to verify a simply version bump would result a good build.  Although it's still best that packagers would still test on personal computer.  This might have to achieve with Docker, if we are going to that, which I have no idea how.  I don't think we have Arch tools on Travis CI, more precisely, on Ubuntu.


## 5

I've put in a section "Packaging" in README, it's meant for brief packaging instructions that details packaging release process (**4**), but we can move it to separate file or wiki.

@StefansM you will decide where the documentation goes to and also write them.


## 6

@StefansM and @Foggalong should have the accounts on AUR.  Perhaps also list @Foggalong as maintainer in `PKGBUILD`?


## 7

What license should we license this repository under?  I think we should go for CC0 or Unlicense or any public domain equivalent license, I don't really think we need to use those more common open source license, all actual codes in this repository probably just snippets.

**Comment by livibetter** [comment]
I am sending an email to invite @Acidhub to join us as @pipeseroni/bash-devs and/or @pipeseroni/aur-packagers packager, or the very least hoping he would provide some thoughts and experiences on the discussions here.

Please note that: if he agrees to join @pipeseroni/aur, @StefansM will have to agree to have him.  As for @pipeseroni/bash-devs, I can put him into the team.

**Comment by StefansM** [comment]
@livibetter, brilliant work. Sorry I haven't had the chance to look at this earlier. I agree with all your points.

---

> Currently, we use branches to store `PKGBUILD` for each pipe

I think this is the best solution, because we can push to the AUR by just configuring a remote and pushing the repo branch to the remote master:

```
git remote add pipes.c ssh://aur@aur.archlinux.org/pipes.c.git
git checkout pipes.c
git push pipes.c pipes.c:master
```

---

> Updating version string
>
> @StefansM has mentioned a way to automate this with git describe

If the `PKGBUILD` is configured to pull directly from git (e.g. `source=("git+https://github.com/pipeseroni/pipes.c.git`), `$pkgver` can be set by the `pkgver()` function:

```bash
pkgver() {
    cd "$srcdir/$_repo"

    # Git, tags available
    printf "%s" "$(\
        git describe --long --tags \
        | sed 's/^v//;s/\([^-]*-\)g/r\1/;s/-/./g')"
}
```

If we're building from releases rather than git, `pkgver` needs to be set manually. It's pretty easy to get the version from the GitHub API with a simple script, though. Since we only merge working pull requests, I think I should just get in the habit of making releases for each commit on the master branch and updating the `PKGBUILD`s to point to the new release.

---

> Updating checksum for integrity check
>
> I used updpkgsums, but it updates with md5sum, can we have hash liks SHA*?

If you replace `md5sums=(...)` with, for example, `sha256sums=()` and run `updpkgsums`, it will detect which hash to use. See #3 and #4.

---

>Generating .SRCINFO
>
>From what I understand, we need to re-generate it every time we update PKGBUILD, so how do we make sure the file is up to date?

I think we should include a `pre-commit` hook in the master branch that automatically runs `makepkg --printsrcinfo > .SRCINFO`, and a `pre-push` hook that

1. Checks the AUR remote being pushed matches the branch name. This should help prevent confusion by giving an informative error message when accidentally trying to push the `pipes.sh` branch to the `pipes.c` master.

2. Checks the `.SRCINFO` in the git index is identical to a `.SRCINFO` generated from the `PKGBUILD` in the index. This should prevent mistakes due to unmerged changes.

---

Most of the time, the updates for the packaging scripts are going to be trivial version number bumps, which will be pretty easy to automate. See #2

**Comment by livibetter** [comment]
@StefansM 

I like the automation (still reading through) and I think if using Git is better for you to work with, then by all means switching to Git.  (I'd against it if our repositories are monsters that require long cloning time)

A couple of things:

- Since you have written several Bash scripts, I think you should choose a license for this repository.

- You can already add you as Maintainer in the `PKGBUILD` files.

**Comment by StefansM** [comment]
@livibetter 

I think having the `PKGBUILD`s use the releases is probably better. It does cause a bit more work, because the project maintainers need to remember to tag their merges (I think you're already good at this, but I will need to get in the habit) and the packagers need to manually bump the version number. If we pull from git, we will need to list `autoconf`, `automake` and `autoconf-archive` as `makedepends` (for pipes.c). Not a huge deal, but I don't like forcing users to install dev tools (even temporarily) just to install a package. I could put `configure` and `Makefile` in the git repository, but I don't like storing generated files in VCS.

I really don't mind which license we use. I think I will just include a link here in a comment and use CC0. People can decide if they want to give credit. My bash scripting isn't great, so maybe it's best if they don't give credit :)

**Comment by livibetter** [comment]
@StefansM 

I didn't think of all the autotools have to be pulled, now I am against using Git.  I also don't like versioning those files, especially when those two generated files are really huge.

CC0 is a good choice.  I think most people's Bash skill isn't great, me included, really not our fault!  Bash, well, it's a complicated *thing*.

**Comment by livibetter** [comment]
This is a reminder note, for next revision/release of pipes.sh, list ncurses as direct dependency as now pipes.sh is relying on `tput` even more (pipeseroni/pipes.sh#56).
